name: Gradle Build & Spotless Check

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the codebase
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Cache Gradle dependencies
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Verify Gradle Wrapper integrity
      - name: Verify Gradle Wrapper
        run: ./gradlew wrapper --gradle-version

      # Run Spotless check
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
        continue-on-error: true

      # Suggest fixes if Spotless Check fails
      - name: Spotless Check Suggestions
        if: failure()
        run: |
          echo "Spotless Check failed. Please run './gradlew spotlessApply' locally to fix formatting issues."
          echo "Commit the changes after running the command."
          exit 1

      # Build the project
      - name: Build Project
        run: ./gradlew build

      # Optional: Run tests (if applicable)
      - name: Run Tests
        run: ./gradlew test
